/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentLoginRouteImport } from './routes/student-login'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentScanRouteImport } from './routes/student.scan'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentHistoryRouteImport } from './routes/student.history'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as FacultyStudentsRouteImport } from './routes/faculty.students'
import { Route as FacultyReportsRouteImport } from './routes/faculty.reports'
import { Route as FacultyProfileRouteImport } from './routes/faculty.profile'
import { Route as FacultyDashboardRouteImport } from './routes/faculty.dashboard'
import { Route as FacultySessionsIndexRouteImport } from './routes/faculty.sessions.index'
import { Route as FacultySessionsIdRouteImport } from './routes/faculty.sessions.$id'

const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student-login',
  path: '/student-login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentScanRoute = StudentScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentHistoryRoute = StudentHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const FacultyStudentsRoute = FacultyStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyReportsRoute = FacultyReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyProfileRoute = FacultyProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyDashboardRoute = FacultyDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultySessionsIndexRoute = FacultySessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultySessionsIdRoute = FacultySessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => FacultyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faculty': typeof FacultyRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/student-login': typeof StudentLoginRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/profile': typeof FacultyProfileRoute
  '/faculty/reports': typeof FacultyReportsRoute
  '/faculty/students': typeof FacultyStudentsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/history': typeof StudentHistoryRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/scan': typeof StudentScanRoute
  '/faculty/sessions/$id': typeof FacultySessionsIdRoute
  '/faculty/sessions/': typeof FacultySessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faculty': typeof FacultyRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/student-login': typeof StudentLoginRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/profile': typeof FacultyProfileRoute
  '/faculty/reports': typeof FacultyReportsRoute
  '/faculty/students': typeof FacultyStudentsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/history': typeof StudentHistoryRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/scan': typeof StudentScanRoute
  '/faculty/sessions/$id': typeof FacultySessionsIdRoute
  '/faculty/sessions': typeof FacultySessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faculty': typeof FacultyRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/student-login': typeof StudentLoginRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/profile': typeof FacultyProfileRoute
  '/faculty/reports': typeof FacultyReportsRoute
  '/faculty/students': typeof FacultyStudentsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/history': typeof StudentHistoryRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/scan': typeof StudentScanRoute
  '/faculty/sessions/$id': typeof FacultySessionsIdRoute
  '/faculty/sessions/': typeof FacultySessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faculty'
    | '/login'
    | '/signup'
    | '/student'
    | '/student-login'
    | '/faculty/dashboard'
    | '/faculty/profile'
    | '/faculty/reports'
    | '/faculty/students'
    | '/student/dashboard'
    | '/student/history'
    | '/student/profile'
    | '/student/scan'
    | '/faculty/sessions/$id'
    | '/faculty/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faculty'
    | '/login'
    | '/signup'
    | '/student'
    | '/student-login'
    | '/faculty/dashboard'
    | '/faculty/profile'
    | '/faculty/reports'
    | '/faculty/students'
    | '/student/dashboard'
    | '/student/history'
    | '/student/profile'
    | '/student/scan'
    | '/faculty/sessions/$id'
    | '/faculty/sessions'
  id:
    | '__root__'
    | '/'
    | '/faculty'
    | '/login'
    | '/signup'
    | '/student'
    | '/student-login'
    | '/faculty/dashboard'
    | '/faculty/profile'
    | '/faculty/reports'
    | '/faculty/students'
    | '/student/dashboard'
    | '/student/history'
    | '/student/profile'
    | '/student/scan'
    | '/faculty/sessions/$id'
    | '/faculty/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FacultyRoute: typeof FacultyRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  StudentRoute: typeof StudentRouteWithChildren
  StudentLoginRoute: typeof StudentLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student-login': {
      id: '/student-login'
      path: '/student-login'
      fullPath: '/student-login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/scan': {
      id: '/student/scan'
      path: '/scan'
      fullPath: '/student/scan'
      preLoaderRoute: typeof StudentScanRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/history': {
      id: '/student/history'
      path: '/history'
      fullPath: '/student/history'
      preLoaderRoute: typeof StudentHistoryRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/faculty/students': {
      id: '/faculty/students'
      path: '/students'
      fullPath: '/faculty/students'
      preLoaderRoute: typeof FacultyStudentsRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/reports': {
      id: '/faculty/reports'
      path: '/reports'
      fullPath: '/faculty/reports'
      preLoaderRoute: typeof FacultyReportsRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/profile': {
      id: '/faculty/profile'
      path: '/profile'
      fullPath: '/faculty/profile'
      preLoaderRoute: typeof FacultyProfileRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/dashboard': {
      id: '/faculty/dashboard'
      path: '/dashboard'
      fullPath: '/faculty/dashboard'
      preLoaderRoute: typeof FacultyDashboardRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/sessions/': {
      id: '/faculty/sessions/'
      path: '/sessions'
      fullPath: '/faculty/sessions/'
      preLoaderRoute: typeof FacultySessionsIndexRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/sessions/$id': {
      id: '/faculty/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/faculty/sessions/$id'
      preLoaderRoute: typeof FacultySessionsIdRouteImport
      parentRoute: typeof FacultyRoute
    }
  }
}

interface FacultyRouteChildren {
  FacultyDashboardRoute: typeof FacultyDashboardRoute
  FacultyProfileRoute: typeof FacultyProfileRoute
  FacultyReportsRoute: typeof FacultyReportsRoute
  FacultyStudentsRoute: typeof FacultyStudentsRoute
  FacultySessionsIdRoute: typeof FacultySessionsIdRoute
  FacultySessionsIndexRoute: typeof FacultySessionsIndexRoute
}

const FacultyRouteChildren: FacultyRouteChildren = {
  FacultyDashboardRoute: FacultyDashboardRoute,
  FacultyProfileRoute: FacultyProfileRoute,
  FacultyReportsRoute: FacultyReportsRoute,
  FacultyStudentsRoute: FacultyStudentsRoute,
  FacultySessionsIdRoute: FacultySessionsIdRoute,
  FacultySessionsIndexRoute: FacultySessionsIndexRoute,
}

const FacultyRouteWithChildren =
  FacultyRoute._addFileChildren(FacultyRouteChildren)

interface StudentRouteChildren {
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentHistoryRoute: typeof StudentHistoryRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentScanRoute: typeof StudentScanRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentDashboardRoute: StudentDashboardRoute,
  StudentHistoryRoute: StudentHistoryRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentScanRoute: StudentScanRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FacultyRoute: FacultyRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  StudentRoute: StudentRouteWithChildren,
  StudentLoginRoute: StudentLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
